import { Client, GatewayIntentBits, Partials } from 'discord.js';
import CONFIG from './src/config.js';
import { LoadCommands } from './src/commands.js';

console.log("Starting Chess...")

const client = new Client({ 
    //This number is generated by discord's bit calculator thing
	intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessageReactions],
	partials: [Partials.Message, Partials.Channel, Partials.Reaction],
});

LoadCommands(client)

client.once('ready', async c => {
	console.log('Chess is logged in');
	client.guilds.cache.forEach(guild => {console.log('Joined server:', guild.name);});
});

client.login(CONFIG.token);